language: generic
sudo: required
services:
- docker
env:
  global:
  - NODE_ENV=test
dist: trusty
cache:
  directories:
  - src/angular/node_modules
  - src/vendor
  - src/e2e/node_modules
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
before_script:
- make install
script:
- make test
