<app-root> 
<nav class="navbar bandeau-navigation navbar-fixed-top" role="navigation" style="margin-bottom:0; height: 60px;">
<div class="container">
<div class="navbar-header"><img style="position:absolute;top:0px;left:-250px;" class="bounce-animation" src="img/cnam_header1.png"/>
<img style="position: absolute; top: 0px; left:380px;" src="img/cnam_header2.png"/></div>
<div class="navbar-header" style="margin-left: 200px;">
<div style="background-color: #C1022D;  position: absolute; height:60px; width: 3000px; top: 0px; left:450px;"></div>
<p class="navbar-brand" style="position:absolute;top:0px;left:450px;color: white;font-size: 38px;  text-shadow: 9px 11px 12px #000000;">
                        Gestion du suivi des présences
                    </p>
                </div>
            </div>
</nav>   
<div class="chargement-appli-tossing"><div class="chargement-appli jumbotron center" 
style="width:300px; border-radius: 50px; float: none;margin-top: 60px; margin-left: auto;margin-right: auto;">
Chargement de l'application... </div> </div>
<div class="spinnerload">
<div class="upper">
<div class="inner"></div>
</div>
<div class="middle"></div>
<div class="lower">
<div class="inner"></div>
</div>
</div>
</app-root>
<script type="text/javascript" src="js/inline.bundle.js"></script>
<script type="text/javascript" src="js/scripts.bundle.js"></script>
<script type="text/javascript" src="js/styles.bundle.js"></script>
<script type="text/javascript" src="js/polyfills.bundle.js"></script>
<script type="text/javascript" src="js/vendor.bundle.js"></script>
<script type="text/javascript" src="js/main.bundle.js"></script>


